# Generated by Django 4.2.4 on 2025-02-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0010_company_created_at_company_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_number', models.PositiveIntegerField(default=11000)),
                ('current_number', models.PositiveIntegerField(default=11000)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.PositiveIntegerField(unique=True)),
                ('offer_date', models.DateField(default=None)),
                ('valid_until', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('project_country', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.contact')),
            ],
        ),
    ]
