# Generated by Django 4.2.4 on 2025-02-07 12:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='project_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
