# Generated by Django 4.2.4 on 2025-02-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='project_name',
            field=models.CharField(default='No project name', max_length=255),
            preserve_default=False,
        ),
    ]
