# Generated by Django 5.1.5 on 2025-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_deliverymethod_offer_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='delivery_time_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
