# Generated by Django 5.1.5 on 2025-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
