# Generated by Django 5.1.5 on 2025-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_offer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
