# Generated by Django 5.1.5 on 2025-01-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='classification',
            field=models.CharField(choices=[('High Value', 'High Value'), ('Medium Value', 'Medium Value'), ('Low Value', 'Low Value'), ('Unimportant', 'Unimportant')], default='Unimportant', max_length=15),
        ),
    ]
