# Generated by Django 5.1.5 on 2025-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='default_user.png', upload_to='contact_images/'),
        ),
    ]
