# Generated by Django 5.1.5 on 2025-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='contact_images/default_user.png', upload_to='contact_images/'),
        ),
    ]
