# Generated by Django 5.1.5 on 2025-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_contact_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='behavior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_communication',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('In-person', 'In-person'), ('Messaging', 'Messaging')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
