# Generated by Django 4.2.18 on 2025-01-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_contact_additional_info_contact_behavior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='social_media_links',
        ),
    ]
