# Generated by Django 4.2.4 on 2025-02-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_production_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='production_time',
            field=models.PositiveIntegerField(help_text='Estimated production time in Weeks'),
        ),
    ]
